/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class east_orientation_lamelibrary_LameUtil */

#ifndef _Included_east_orientation_caster_cast_LameUtil
#define _Included_east_orientation_caster_cast_LameUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     east_orientation_lamelibrary_LameUtil
 * Method:    init
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_east_orientation_lamelibrary_LameUtil_init
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     east_orientation_lamelibrary_LameUtil
 * Method:    encode
 * Signature: ([S[SI[B)I
 */
JNIEXPORT jint JNICALL Java_east_orientation_lamelibrary_LameUtil_encode
  (JNIEnv *, jclass, jshortArray, jshortArray, jint, jbyteArray);

/*
 * Class:     east_orientation_lamelibrary_LameUtil
 * Method:    flush
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_east_orientation_lamelibrary_LameUtil_flush
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     east_orientation_lamelibrary_LameUtil
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_east_orientation_lamelibrary_LameUtil_close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
